### PR TITLE
creating a new ogrdb api, and an UI to make requests

### PR DESCRIPTION
**Pull request by yanivm96**
New api for ogrdb, implemented in api_v1 folder, placed along side with models.py that was created with pydantic’s code generator.
The UI was implemented with swagger-ui

### CODE REVIEW

**Comment by schristley** [comment]
@yanivm96 @williamdlees Is the plan to keep both the older V1 API and the new V2 openapi3 API available in OGRDB, or discontinue the V1 API? I'm not sure if you have users and/or integrations that are actively using the V1 API, then you might want to keep both actively while you actively encourage moving to V2.

**Comment by schristley** [comment]
It is also unclear to me what is the purpose of the `static/swagger.yml` file? It looks to be the same as the openapi3 spec file, why two files?

**Comment by williamdlees** [comment]
yes we will need to keep v1 I think.will come back with some comments on v2 when we have experience using it to build this command line utility.Yaniv can you answer the question on the swagger file, thanks.On 9 Jun 2024, at 20:17, Scott Christley ***@***.***> wrote:﻿
@yanivm96 @williamdlees Is the plan to keep both the older V1 API and the new V2 openapi3 API available in OGRDB, or discontinue the V1 API? I'm not sure if you have users and/or integrations that are actively using the V1 API, then you might want to keep both actively while you actively encourage moving to V2.

**Comment by yanivm96** [comment]
Hey, you are right, I will change it to use
the ogrdb-api-openapi3.yaml file.

‫בתאריך יום א׳, 9 ביוני 2024 ב-22:33 מאת ‪William Lees‬‏ <‪
***@***.***‬‏>:‬

**Comment by yanivm96** [comment]
adding endpoint for request all avaiable versions, and endpoint for request format type

**Pull request closed without merging**
